<?php
return array (
  'title' => '行业分类',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '婴儿服饰',
      'style' => '0',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3361',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'clothes',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '孕妇用品',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3362,3396,3397,3398,3399',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'yun',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '婴童食品',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3363,3388,3389,3390',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'food',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3364 => 
    array (
      'linkageid' => '3364',
      'name' => '婴童用品',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3364,3380,3381,3382,3383',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'yong',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '洗护用品',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3365,3384,3385,3386,3387',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'xihu',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '婴童鞋',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3367,3411,3412',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'shoes',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '婴童玩具',
      'style' => '0',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3368,3400,3401,3402,3403,3404,3405,3406,3407,3408,3409,3410',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => 'toys',
      'setting' => 'array (
  \'level\' => \'0\',
)',
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '寝居用品',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3369,3391,3392,3393',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '出行用品',
      'style' => '',
      'parentid' => '0',
      'child' => '1',
      'arrchildid' => '3370,3394,3395',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => '儿童服装',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3371',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '孕婴童生活馆',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3372',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '婴童教育',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3373',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '孕婴机构',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '3374',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3380 => 
    array (
      'linkageid' => '3380',
      'name' => '哺喂用品',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3380',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3381 => 
    array (
      'linkageid' => '3381',
      'name' => '婴童纪念品',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3381',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3382 => 
    array (
      'linkageid' => '3382',
      'name' => '健康安全用品',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3382',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3383 => 
    array (
      'linkageid' => '3383',
      'name' => '婴童电器用品',
      'style' => '',
      'parentid' => '3364',
      'child' => '0',
      'arrchildid' => '3383',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3384 => 
    array (
      'linkageid' => '3384',
      'name' => '婴童防尿用品',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3384',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3385 => 
    array (
      'linkageid' => '3385',
      'name' => '婴童洗浴用品',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3385',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3386 => 
    array (
      'linkageid' => '3386',
      'name' => '婴童护肤用品',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3386',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3387 => 
    array (
      'linkageid' => '3387',
      'name' => '衣物洗涤用品',
      'style' => '',
      'parentid' => '3365',
      'child' => '0',
      'arrchildid' => '3387',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3388 => 
    array (
      'linkageid' => '3388',
      'name' => '婴童奶粉',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3388',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3389 => 
    array (
      'linkageid' => '3389',
      'name' => '婴童辅食',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3389',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3390 => 
    array (
      'linkageid' => '3390',
      'name' => '婴童保健品',
      'style' => '',
      'parentid' => '3363',
      'child' => '0',
      'arrchildid' => '3390',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3391 => 
    array (
      'linkageid' => '3391',
      'name' => '婴童家纺',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3391',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3392 => 
    array (
      'linkageid' => '3392',
      'name' => '童床',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3392',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3393 => 
    array (
      'linkageid' => '3393',
      'name' => '儿童家具',
      'style' => '',
      'parentid' => '3369',
      'child' => '0',
      'arrchildid' => '3393',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3394 => 
    array (
      'linkageid' => '3394',
      'name' => '童车',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3394',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3395 => 
    array (
      'linkageid' => '3395',
      'name' => '安全座椅',
      'style' => '',
      'parentid' => '3370',
      'child' => '0',
      'arrchildid' => '3395',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3396 => 
    array (
      'linkageid' => '3396',
      'name' => '孕妇服饰',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3396',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3397 => 
    array (
      'linkageid' => '3397',
      'name' => '孕妇护理品',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3397',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3398 => 
    array (
      'linkageid' => '3398',
      'name' => '孕妇食品',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3398',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3399 => 
    array (
      'linkageid' => '3399',
      'name' => '孕妇鞋',
      'style' => '',
      'parentid' => '3362',
      'child' => '0',
      'arrchildid' => '3399',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3400 => 
    array (
      'linkageid' => '3400',
      'name' => '木质玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3400',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3401 => 
    array (
      'linkageid' => '3401',
      'name' => '人偶玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3401',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3402 => 
    array (
      'linkageid' => '3402',
      'name' => '毛绒玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3402',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3403 => 
    array (
      'linkageid' => '3403',
      'name' => '遥控玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3403',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3404 => 
    array (
      'linkageid' => '3404',
      'name' => '益智玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3404',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3405 => 
    array (
      'linkageid' => '3405',
      'name' => '布艺玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3405',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3406 => 
    array (
      'linkageid' => '3406',
      'name' => '塑胶玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3406',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3407 => 
    array (
      'linkageid' => '3407',
      'name' => '电动玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3407',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3408 => 
    array (
      'linkageid' => '3408',
      'name' => '电子玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3408',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3409 => 
    array (
      'linkageid' => '3409',
      'name' => '模型玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3409',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3410 => 
    array (
      'linkageid' => '3410',
      'name' => '魔术玩具',
      'style' => '',
      'parentid' => '3368',
      'child' => '0',
      'arrchildid' => '3410',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3411 => 
    array (
      'linkageid' => '3411',
      'name' => '婴儿鞋',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3411',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3412 => 
    array (
      'linkageid' => '3412',
      'name' => '童鞋',
      'style' => '',
      'parentid' => '3367',
      'child' => '0',
      'arrchildid' => '3412',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>