<?php
return array (
  47 => 
  array (
    'catid' => '47',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '47',
    'catname' => '供应',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=lists&catid=47',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '47',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'gongying',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  48 => 
  array (
    'catid' => '48',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '48',
    'catname' => '找品牌',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=lists&catid=48',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '48',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'zhaopinpai',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  49 => 
  array (
    'catid' => '49',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '49',
    'catname' => '招加盟',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=lists&catid=49',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '49',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'zhaojiameng',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  50 => 
  array (
    'catid' => '50',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '14',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '50',
    'catname' => '招经销',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=lists&catid=50',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '50',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'zhaojingxiao',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
);
?>