<?php
return array (
  31 => 
  array (
    'catid' => '31',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '31',
    'catname' => '婴儿服饰',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=list_company&catid=31',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '31',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingerfushi',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  32 => 
  array (
    'catid' => '32',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '32',
    'catname' => '孕妇用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=list_company&catid=32',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '32',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yunfuyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  33 => 
  array (
    'catid' => '33',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '33',
    'catname' => '婴儿食品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=list_company&catid=33',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '33',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingershipin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  34 => 
  array (
    'catid' => '34',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '34',
    'catname' => '婴儿用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=list_company&catid=34',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '34',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingeryongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  35 => 
  array (
    'catid' => '35',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '35',
    'catname' => '洗护用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=list_company&catid=35',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '35',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xihuyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  36 => 
  array (
    'catid' => '36',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '36',
    'catname' => '童车',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=list_company&catid=36',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '36',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'tongche',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  37 => 
  array (
    'catid' => '37',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '37',
    'catname' => '童鞋',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=list_company&catid=37',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '37',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'tongxie',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  38 => 
  array (
    'catid' => '38',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '38',
    'catname' => '玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com/index.php?m=yp&c=index&a=list_company&catid=38',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
  \'meta_title\' => \'\',
  \'meta_keywords\' => \'\',
  \'meta_description\' => \'\',
)',
    'listorder' => '38',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'wanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
);
?>