<?php
return array (
  3361 => 
  array (
    'catid' => '3361',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '3361',
    'catname' => '婴儿服饰',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3361',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingerfushi',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3362 => 
  array (
    'catid' => '3362',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '3362,3396,3397,3398,3399',
    'catname' => '孕妇用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3362',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yunfuyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3363 => 
  array (
    'catid' => '3363',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '3363,3388,3389,3390',
    'catname' => '婴童食品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3363',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongshipin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3364 => 
  array (
    'catid' => '3364',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '3364,3380,3381,3382,3383',
    'catname' => '婴童用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3364',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3365 => 
  array (
    'catid' => '3365',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '3365,3384,3385,3386,3387',
    'catname' => '洗护用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3365',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'xihuyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3367 => 
  array (
    'catid' => '3367',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '3367,3411,3412',
    'catname' => '婴童鞋',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3367',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongxie',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3368 => 
  array (
    'catid' => '3368',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '3368,3400,3401,3402,3403,3404,3405,3406,3407,3408,3409,3410',
    'catname' => '婴童玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3368',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3369 => 
  array (
    'catid' => '3369',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '3369,3391,3392,3393',
    'catname' => '寝居用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3369',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'qinjuyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3370 => 
  array (
    'catid' => '3370',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '1',
    'arrchildid' => '3370,3394,3395',
    'catname' => '出行用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3370',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'chuxingyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3371 => 
  array (
    'catid' => '3371',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '3371',
    'catname' => '儿童服装',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3371',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'ertongfuzhuang',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3372 => 
  array (
    'catid' => '3372',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '3372',
    'catname' => '孕婴童生活馆',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3372',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yunyingtongshenghuoguan',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3373 => 
  array (
    'catid' => '3373',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '3373',
    'catname' => '婴童教育',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3373',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongjiaoyu',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3374 => 
  array (
    'catid' => '3374',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '3374',
    'catname' => '孕婴机构',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3374',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yunyingjigou',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3380 => 
  array (
    'catid' => '3380',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3364',
    'arrparentid' => '0,3364',
    'child' => '0',
    'arrchildid' => '3380',
    'catname' => '哺喂用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3380',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'buweiyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3381 => 
  array (
    'catid' => '3381',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3364',
    'arrparentid' => '0,3364',
    'child' => '0',
    'arrchildid' => '3381',
    'catname' => '婴童纪念品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3381',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongjinianpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3382 => 
  array (
    'catid' => '3382',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3364',
    'arrparentid' => '0,3364',
    'child' => '0',
    'arrchildid' => '3382',
    'catname' => '健康安全用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3382',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'jiankanganquanyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3383 => 
  array (
    'catid' => '3383',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3364',
    'arrparentid' => '0,3364',
    'child' => '0',
    'arrchildid' => '3383',
    'catname' => '婴童电器用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3383',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongdianqiyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3384 => 
  array (
    'catid' => '3384',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3365',
    'arrparentid' => '0,3365',
    'child' => '0',
    'arrchildid' => '3384',
    'catname' => '婴童防尿用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3384',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongfangniaoyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3385 => 
  array (
    'catid' => '3385',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3365',
    'arrparentid' => '0,3365',
    'child' => '0',
    'arrchildid' => '3385',
    'catname' => '婴童洗浴用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3385',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongxiyuyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3386 => 
  array (
    'catid' => '3386',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3365',
    'arrparentid' => '0,3365',
    'child' => '0',
    'arrchildid' => '3386',
    'catname' => '婴童护肤用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3386',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtonghufuyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3387 => 
  array (
    'catid' => '3387',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3365',
    'arrparentid' => '0,3365',
    'child' => '0',
    'arrchildid' => '3387',
    'catname' => '衣物洗涤用品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3387',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yiwuxidiyongpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3388 => 
  array (
    'catid' => '3388',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3363',
    'arrparentid' => '0,3363',
    'child' => '0',
    'arrchildid' => '3388',
    'catname' => '婴童奶粉',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3388',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongnaifen',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3389 => 
  array (
    'catid' => '3389',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3363',
    'arrparentid' => '0,3363',
    'child' => '0',
    'arrchildid' => '3389',
    'catname' => '婴童辅食',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3389',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongfushi',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3390 => 
  array (
    'catid' => '3390',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3363',
    'arrparentid' => '0,3363',
    'child' => '0',
    'arrchildid' => '3390',
    'catname' => '婴童保健品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3390',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongbaojianpin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3391 => 
  array (
    'catid' => '3391',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3369',
    'arrparentid' => '0,3369',
    'child' => '0',
    'arrchildid' => '3391',
    'catname' => '婴童家纺',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3391',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingtongjiafang',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3392 => 
  array (
    'catid' => '3392',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3369',
    'arrparentid' => '0,3369',
    'child' => '0',
    'arrchildid' => '3392',
    'catname' => '童床',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3392',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'tongchuang',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3393 => 
  array (
    'catid' => '3393',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3369',
    'arrparentid' => '0,3369',
    'child' => '0',
    'arrchildid' => '3393',
    'catname' => '儿童家具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3393',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'ertongjiaju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3394 => 
  array (
    'catid' => '3394',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3370',
    'arrparentid' => '0,3370',
    'child' => '0',
    'arrchildid' => '3394',
    'catname' => '童车',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3394',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'tongche',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3395 => 
  array (
    'catid' => '3395',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3370',
    'arrparentid' => '0,3370',
    'child' => '0',
    'arrchildid' => '3395',
    'catname' => '安全座椅',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3395',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'anquanzuoyi',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3396 => 
  array (
    'catid' => '3396',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3362',
    'arrparentid' => '0,3362',
    'child' => '0',
    'arrchildid' => '3396',
    'catname' => '孕妇服饰',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3396',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yunfufushi',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3397 => 
  array (
    'catid' => '3397',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3362',
    'arrparentid' => '0,3362',
    'child' => '0',
    'arrchildid' => '3397',
    'catname' => '孕妇护理品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3397',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yunfuhulipin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3398 => 
  array (
    'catid' => '3398',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3362',
    'arrparentid' => '0,3362',
    'child' => '0',
    'arrchildid' => '3398',
    'catname' => '孕妇食品',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3398',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yunfushipin',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3399 => 
  array (
    'catid' => '3399',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3362',
    'arrparentid' => '0,3362',
    'child' => '0',
    'arrchildid' => '3399',
    'catname' => '孕妇鞋',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3399',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yunfuxie',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3400 => 
  array (
    'catid' => '3400',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3400',
    'catname' => '木质玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3400',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'muzhiwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3401 => 
  array (
    'catid' => '3401',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3401',
    'catname' => '人偶玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3401',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'renouwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3402 => 
  array (
    'catid' => '3402',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3402',
    'catname' => '毛绒玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3402',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'maorongwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3403 => 
  array (
    'catid' => '3403',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3403',
    'catname' => '遥控玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3403',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yaokongwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3404 => 
  array (
    'catid' => '3404',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3404',
    'catname' => '益智玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3404',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yizhiwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3405 => 
  array (
    'catid' => '3405',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3405',
    'catname' => '布艺玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3405',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'buyiwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3406 => 
  array (
    'catid' => '3406',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3406',
    'catname' => '塑胶玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3406',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'sujiaowanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3407 => 
  array (
    'catid' => '3407',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3407',
    'catname' => '电动玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3407',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'diandongwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3408 => 
  array (
    'catid' => '3408',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3408',
    'catname' => '电子玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3408',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'dianziwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3409 => 
  array (
    'catid' => '3409',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3409',
    'catname' => '模型玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3409',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'moxingwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3410 => 
  array (
    'catid' => '3410',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3368',
    'arrparentid' => '0,3368',
    'child' => '0',
    'arrchildid' => '3410',
    'catname' => '魔术玩具',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3410',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'moshuwanju',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3411 => 
  array (
    'catid' => '3411',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3367',
    'arrparentid' => '0,3367',
    'child' => '0',
    'arrchildid' => '3411',
    'catname' => '婴儿鞋',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3411',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'yingerxie',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
  3412 => 
  array (
    'catid' => '3412',
    'siteid' => '1',
    'type' => '0',
    'modelid' => '11',
    'parentid' => '3367',
    'arrparentid' => '0,3367',
    'child' => '0',
    'arrchildid' => '3412',
    'catname' => '童鞋',
    'style' => '',
    'image' => '',
    'description' => '',
    'parentdir' => '',
    'url' => 'http://www.baobei.com//index.php?m=yp&c=index&a=list_company&catid=3412',
    'items' => '0',
    'hits' => '0',
    'setting' => 'array (
			  \'meta_title\' => \'\',
			  \'meta_keywords\' => \'\',
			  \'meta_description\' => \'\',
			)',
    'listorder' => '0',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'tongxie',
    'usable_type' => '',
    'additional' => '',
    'commenttypeid' => '0',
    'meta_title' => '',
    'meta_keywords' => '',
    'meta_description' => '',
  ),
);
?>